---
title: "formula_2_23"
output: github_document
---

### What research question do you want to answer?

Do SCOTUS justices use more critical language when ruling on actions of administrations of opposing party identification? Is there a time-series effect?

### What are two possible answers?

Yes, justices are more likely to use critical language about administrative actions when dealing with executives of opposing parties. (Alternatively, no, they don't!)

### What are the documents of text data you will analyze?

SCOTUS opinions, including dissents.

### Give two examples of documents in the corpus that you expect will be high in similarity to each other? Two examples that are *low* in similarity?

Sotomayor's dissent in U.S. v. Higgs (criticizing rushed death penalties) + probably something Scalia wrote about Obama (there's a lot of topical language at play in each case, so isolating language that is critical--The Administration *rushed*, is *prejudiced*, etc. needs to be drawn out to facilitate comparisons.) Meanwhile, Sotomayor's dissent will probably be very dissimilar to Thomas- or Scalia-led opinions under the Bush administration where there was a "conservative" majority.